#! /bin/sh

killall -q polybar

while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

polybar main &
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -model abnt2 -layout br &
	picom &
~/.fehbg &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^5'
bspc rule -a firefox desktop='^1'



